# =========================================================
#  HoneyFile Monitor – Auto-Start Setup
#  Two methods tried:
#    1. Task Scheduler (preferred – silent, no window)
#    2. Startup Folder VBScript (fallback – always works)
# =========================================================

$TaskName   = "HoneyFileMonitor"
$ScriptPath = "d:\Honey_file_project\main.py"
$PythonExe  = (Get-Command python -ErrorAction SilentlyContinue).Source

if (-not $PythonExe) {
    Write-Host "[ERROR] Python not found in PATH. Install Python and retry." -ForegroundColor Red
    exit 1
}

Write-Host "[*] Python found at: $PythonExe" -ForegroundColor Cyan

# ---- METHOD 1: Task Scheduler ----
$taskRegistered = $false
try {
    # Remove existing task if it exists
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "[*] Removed existing task." -ForegroundColor Yellow
    }

    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name

    $action = New-ScheduledTaskAction `
        -Execute $PythonExe `
        -Argument "`"$ScriptPath`"" `
        -WorkingDirectory "d:\Honey_file_project"

    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $currentUser

    $principal = New-ScheduledTaskPrincipal `
        -UserId $currentUser `
        -LogonType Interactive `
        -RunLevel Highest

    $settings = New-ScheduledTaskSettingsSet `
        -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
        -RestartCount 3 `
        -RestartInterval (New-TimeSpan -Minutes 1) `
        -StartWhenAvailable `
        -Hidden

    Register-ScheduledTask `
        -TaskName   $TaskName `
        -Action     $action `
        -Trigger    $trigger `
        -Principal  $principal `
        -Settings   $settings `
        -Description "Starts the HoneyFile Monitor automatically at login" `
        -ErrorAction Stop | Out-Null

    $taskRegistered = $true
    Write-Host ""
    Write-Host "[OK] Task Scheduler method succeeded!" -ForegroundColor Green
    Write-Host "     HoneyFile Monitor will auto-start every time you log in." -ForegroundColor Green
}
catch {
    Write-Host "[!] Task Scheduler method failed: $_" -ForegroundColor Yellow
    Write-Host "    Falling back to Startup Folder method..." -ForegroundColor Yellow
}

# ---- METHOD 2: Startup Folder VBScript (fallback) ----
if (-not $taskRegistered) {
    $startupFolder = [System.Environment]::GetFolderPath("Startup")
    $vbsPath = Join-Path $startupFolder "HoneyFileMonitor.vbs"

    $vbsContent = @"
' Auto-generated by setup_autostart.ps1
' Runs HoneyFile Monitor silently (no console window)
Set oShell = CreateObject("WScript.Shell")
oShell.Run """$PythonExe"" ""$ScriptPath""", 0, False
"@

    Set-Content -Path $vbsPath -Value $vbsContent -Encoding ASCII
    Write-Host ""
    Write-Host "[OK] Startup Folder method succeeded!" -ForegroundColor Green
    Write-Host "     Shortcut placed at: $vbsPath" -ForegroundColor Green
    Write-Host "     HoneyFile Monitor will auto-start every time you log in." -ForegroundColor Green
}

Write-Host ""
Write-Host "Useful commands:" -ForegroundColor Cyan
Write-Host "  Start now  : Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  Stop task  : Stop-ScheduledTask  -TaskName '$TaskName'"
Write-Host "  Remove task: Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
Write-Host "  Remove VBS : Remove-Item `"$([System.Environment]::GetFolderPath('Startup'))\HoneyFileMonitor.vbs`""
